-- MySQL Script generated by MySQL Workbench
-- ven. 09 oct. 2020 09:26:27 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`entreprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entreprises` (
  `identreprise` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  PRIMARY KEY (`identreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`annonces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`annonces` (
  `idannonces` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `entreprise` VARCHAR(45) NOT NULL,
  `poste` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `typecontrat` VARCHAR(45) NOT NULL,
  `descriptionbreve` VARCHAR(100) NOT NULL,
  `grossedescription` VARCHAR(500) NOT NULL,
  `entreprise_identreprise` INT NOT NULL,
  PRIMARY KEY (`idannonces`),
  INDEX `fk_annonces_entreprise1_idx` (`entreprise_identreprise` ASC) VISIBLE,
  CONSTRAINT `fk_annonces_entreprise1`
    FOREIGN KEY (`entreprise_identreprise`)
    REFERENCES `mydb`.`entreprises` (`identreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`postulants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`postulants` (
  `idpostulants` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `tel` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `pseudo` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  PRIMARY KEY (`idpostulants`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`annonces_has_postulants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`annonces_has_postulants` (
  `annonces_idannonces` INT NOT NULL,
  `postulants_idpostulants` INT NOT NULL,
  PRIMARY KEY (`annonces_idannonces`, `postulants_idpostulants`),
  INDEX `fk_annonces_has_postulants_postulants1_idx` (`postulants_idpostulants` ASC) VISIBLE,
  INDEX `fk_annonces_has_postulants_annonces_idx` (`annonces_idannonces` ASC) VISIBLE,
  CONSTRAINT `fk_annonces_has_postulants_annonces`
    FOREIGN KEY (`annonces_idannonces`)
    REFERENCES `mydb`.`annonces` (`idannonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonces_has_postulants_postulants1`
    FOREIGN KEY (`postulants_idpostulants`)
    REFERENCES `mydb`.`postulants` (`idpostulants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `idmessages` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT(4000) NULL,
  `emetteur` VARCHAR(255) NULL,
  `destinataire` VARCHAR(255) NULL,
  `postulants_idpostulants` INT NOT NULL,
  PRIMARY KEY (`idmessages`),
  INDEX `fk_messages_postulants1_idx` (`postulants_idpostulants` ASC) VISIBLE,
  CONSTRAINT `fk_messages_postulants1`
    FOREIGN KEY (`postulants_idpostulants`)
    REFERENCES `mydb`.`postulants` (`idpostulants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
